### ISSUE TITLE
Cannot extract release

### ISSUE THREAD

**Issue by ShadowPauler** [Stanley-GF/Discord-Rainbow-Role#1]
It's saying 24 bytes, and everytime I test the archive or extract it, it tells me there are no errors but there is nothing in the archive???

**Comment by Stanley-GF** [comment]
uh, this is the mediafire for direct download 
https://www.mediafire.com/file/zy3hsgh8jfil1n6/Mabel_Rainbow.sln/file

not forget, open, enter a bot token, select 1, copy the server id, copy the role id, the bot must be higher !

**Comment by ShadowPauler** [comment]
Thanks :D

I also had issues finding the .exe and I was lost a little. If anybody comes across this, it's in the messy amount of files if you think there is no .exe Thanks!
